### ISSUE TITLE
Logo Design

### ISSUE THREAD

**Issue by zularizal** [ramk94/numberconverter#1]
Hi @ramk94 ,  I'm a graphic designer, after I review your project, I'm interested in your project and I want to contribute by creating a logo/icon for your project. What do you think?

**Comment by ramk94** [comment]
Hello @zularizal,
Yes, logo would be great. Thank you for your interest.

Thanks,
Ram

**Comment by ramk94** [comment]
Hello @zularizal,
The icon and Logo are looking good. Really smart thinking. 
Thanks.

**Comment by zularizal** [comment]
Hi, I have uploaded the logo to the drive.

https://drive.google.com/drive/folders/10DdtM4VrNglxGZ1swdlByVWjXL4exOzk?usp=sharing

And also I have sent a pull request to you #2

**Comment by ramk94** [comment]
Thank you very much. 
Best,
Ram
